CRAZYFROG_URL = "https://www.youtube.com/watch?v=PzE6ti2_Oo8"
CRAZYFROG_IMAGES = [
    "https://i.ytimg.com/vi/k85mRPqvMbE/mqdefault.jpg",
    "https://i.ytimg.com/vi/EQozbKOh6nY/hqdefault.jpg",
    "https://phoneky.co.uk/thumbs/screensavers/down/abstract/crazyfrogg_e6lfuqz6.gif",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwilJbtD314ZJSMLFVkesi0kwP9pf6rnWwrg&usqp=CAU",
    "https://studiosol-a.akamaihd.net/uploadfile/letras/fotos/d/c/7/0/dc7011d1e16d3d500f8b5374cd0731cc.jpg",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQx77KpROFNDBA3jAs2tkhvVs_-bjqRbp7_JQ&usqp=CAU",
    "https://i.ytimg.com/vi/S_IAqwrvEuU/maxresdefault.jpg",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkXlXDgxZZ_91UV07HoIp5ZzfWUluRgD9p1g&usqp=CAU",
    "https://i.ytimg.com/vi/TOGusJon6qw/maxresdefault.jpg",
    "https://crazyfrog.tv/assets/img/HEADER_CRAZY-FROG.jpg",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0CSeWUKIYEMI68GZmSLT8DluPXF1hmfB-wg&usqp=CAU",
    "https://media.adultnode.com/uploads/photos/2021/01/adultnode_cb4a2ddbaf584b53290361e76f1234bf.png",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDw77kqDQo1A53SkvLfs8CbC7l6s5A2xEPtw&usqp=CAU",
    "https://ehgt.org/t/2b/80/2b804faf4f24f4f9670cfe134595344b9b575edb-298653-1133-967-png_l.jpg",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpd-4Ing6oCCmERD1I6dfQKZz9RyXrn8tzMQ&usqp=CAU",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSof6nmOfz54zv6byGnFzkjNMDnO5MQYARhEw&usqp=CAU",
    "https://cdn.discordapp.com/attachments/389094746569834509/815343803803107349/EC_UhhrXsAE_Xfo.png",
    "https://media.sketchfab.com/models/62aa800fb9214e8fa126c00304d7bdb1/thumbnails/5d4c65434d024d789f967280563d52b6/7d613ab3c24648e1b7b7518d3d99d48f.jpeg",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKloajGbhTyVn0G0jBUPT1ZUyDa25dz163-g&usqp=CAU",
    "https://media.gettyimages.com/photos/crazy-frog-during-fight-for-life-fundraiser-december-12-2005-at-hard-picture-id134740624?s=612x612",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXUR2lXclE6MeTDE9Hhu8sXsdFn2hfBMVF1w&usqp=CAU",
    "https://pbs.twimg.com/profile_images/423522916/monalisa_mona-crazy-frog_2_400x400.jpg",
    "https://pics.me.me/create-meme-chundra-chuchundra-chundra-chuchundra-crazy-frog-53748802.png",
    "https://i.kym-cdn.com/photos/images/original/000/302/654/bb0.jpg",
    "https://i.ebayimg.com/images/g/MVUAAOxy06hSFSq5/s-l300.jpg",
    "https://cdn.discordapp.com/attachments/389094746569834509/815346365998956564/unknown.png",
]
CRAZYFROG_FRASES = [
    "Crazy frog fugindo da policia",
    "Crazy frog fumando maconha",
    "Crazy frog vs Rodrogas who is more fuck",
    "Primo distante de crazy frog Terry Morcegão",
    "Imagem rara do Crazy Frog bombardeando Hiroshima",
    "Crazy Frog Ahegao",
    "Crazy Frog poetakkkk",
    "Crazy frog correndo em seu habitat natural",
    "Crazy frog de férias",
    "Crazy Frog racer 2",
    "Crazy frog says trans rights",
    "Crazy Frog João Paulo",
    "Rodrogas crazy frog",
    "Crazy Frog Crazy hits",
    "Crazy frog rodrogas",
    "Crazy Frog perdendo o carro porque não pagou o parquímetro",
    "Sabia que o savian sabia assobiar??",
    "Crazy Frog discoteca",
    "Crazy frog presents more crazy hits",
    "Crazy Frog pelúcia",
    "Crazy frog sapo maluco",
    "Crazy Frog pintudo",
    "Crazy Frog furioso",
    "Crazy frog presents crazy Christmas",
    "Crazy Frog secsokkkk",
    "Crazy Frog crucificado",
    "Creize frogue",
    "Crazy Frog Blender",
    "Frog Crazy",
    "Exército de Crazy Frog",
    "Crayzer Frogger",
    "Crazy Frog Afro",
    "crazy Frog de calça",
    "5 Crazy frogs contra 8 savianos, quem ganha?",
    "Sabia que o Crazy Frog sabia assobiar?",
]
CRAZYFROG_MUSICAS = [
    "https://www.youtube.com/watch?v=k85mRPqvMbE&ab_channel=CrazyFrog",
    "https://www.youtube.com/watch?v=0kXwW6reObk&ab_channel=CrazyFrog",
    "https://www.youtube.com/watch?v=P1KT_I1LmtA&ab_channel=CrazyFrog",
    "https://www.youtube.com/watch?v=S_IAqwrvEuU&ab_channel=CrazyFrog",
    "https://www.youtube.com/watch?v=TOGusJon6qw&ab_channel=CrazyFrog",
    "https://www.youtube.com/watch?v=S6rZtIipew8&ab_channel=CrazyFrog",
    "https://www.youtube.com/watch?v=10HwmvvxlEw&ab_channel=CrazyFrog",
    "https://www.youtube.com/watch?v=jwI1j7sslYI&ab_channel=CrazyFrog",
    "https://www.youtube.com/watch?v=_5SfNi71nd8&ab_channel=CrazyFrog",
    "https://www.youtube.com/watch?v=jLPYnw17GTY&ab_channel=CrazyFrog",
    "https://www.youtube.com/watch?v=ua1LGVE9lvY&ab_channel=CrazyFrog",
    "https://www.youtube.com/watch?v=KRbsco8M7Fc&ab_channel=CrazyFrog",
    "https://www.youtube.com/watch?v=FSNXhmBxRKE&ab_channel=CrazyFrog",
]
CRAZYFROG_PREFIX = "cf:"
